In [1]:
import pandas as pd
import numpy as np

### Q1 Pandas version

In [2]:
pd.__version__

'3.0.6'

### Getting the data

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [ ]:
df.head()

### Q2 Records count

In [5]:
df.shape[0]

10000

### Q2 Fuel types

In [6]:
df["fuel_type"].nunique()

3

### Q4 Missing values

In [7]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

### Q5 Max fuel efficiency

In [8]:
df["fuel_efficiency_mpg"].max()

np.float64(41.2)

### Q6 Median value of horsepower

In [9]:
df["horsepower"].median()

np.float64(254.0)

In [10]:
df["horsepower"].mode()

0    252.0
Name: horsepower, dtype: float64

In [11]:
df["horsepower"] = df["horsepower"].fillna(df["horsepower"].mode()[0])

In [12]:
df["horsepower"].median()

np.float64(252.0)

### Q7 Sum of weights

In [13]:
#All cars from Asia
df[
    df["origin"] == "Asia"
]

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [14]:
#Only columns vehicle_weight and model_year
vw_my = df[
    ["vehicle_weight","model_year"]
    ]
print(vw_my)

      vehicle_weight  model_year
0               3870        2006
1               4210        2008
2               4240        1996
3               4490        1989
4               4510        1994
...              ...         ...
9995            4690        2005
9996            4370        1993
9997            4590        2014
9998            4450        2004
9999            4370        2011

[10000 rows x 2 columns]

In [15]:
#First 7 values
vw_my.head(n=7)

   vehicle_weight  model_year
0            3870        2006
1            4210        2008
2            4240        1996
3            4490        1989
4            4510        1994
5            4260        2007
6            4310        1992

In [16]:
#Underlying NumPy array
X = vw_my.values
print(X)

[[3870 2006]
 [4210 2008]
 [4240 1996]
 ...
 [4590 2014]
 [4450 2004]
 [4370 2011]]

In [17]:
#Matrix-matrix multiplication between the transpose of X and X
XTX = X.dot(X.T)
print(XTX)

[[19000936 20320748 20412776 ... 21803384 21241524 20945966]
 [20320748 21756164 21858368 ... 23368012 22758532 22435788]
 [20412776 21858368 21961616 ... 23481544 22867984 22542756]
 ...
 [21803384 23368012 23481544 ... 25124296 24461556 24108454]
 [21241524 22758532 22867984 ... 24461556 23818516 23476544]
 [20945966 22435788 22542756 ... 24108454 23476544 23141021]]

In [ ]:
#Inverse of XTX
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

In [1]:
#Creating array y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

NameError: name 'np' is not defined

In [2]:
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y
w = XTX_inv.dot(X.T).dot(y)

NameError: name 'XTX_inv' is not defined